-- Gen 1 Pokemon move data - all moves used by Generation 5 Pokemon
-- Auto-generated from veekun/pokedex data

-- Physical vs special split (Gen I style: determined by type)
local specialTypes <const> = {
    fire = true, water = true, electric = true,
    grass = true, ice = true, psychic = true, dragon = true,
    dark = true,
}

function getMoveCategory(moveType)
    return specialTypes[moveType] and "special" or "physical"
end

-- ============================================================
-- EFFECT CLASSES — composable battle effects
-- ============================================================

Class("StatChange")
function StatChange:init(target, stat, stages)
    self.target = target
    self.stat = stat
    self.stages = stages
end

function StatChange:apply(attacker, defender)
    local target = self.target == "attacker" and attacker or defender
    local oldStage = target.statStages[self.stat] or 0
    local newStage = math.max(-6, math.min(6, oldStage + self.stages))
    target.statStages[self.stat] = newStage
    local changed = newStage - oldStage
    return { type = "statChange", target = self.target, stat = self.stat, stages = changed, pokemon = target }
end

Class("ConditionalEffect")
function ConditionalEffect:init(chance, effect)
    self.chance = chance
    self.effect = effect
end

function ConditionalEffect:apply(attacker, defender)
    if math.random(1, 100) <= self.chance then
        return self.effect:apply(attacker, defender)
    end
    return nil
end

Class("StatusEffect")
function StatusEffect:init(target, status)
    self.target = target
    self.status = status
end

function StatusEffect:apply(attacker, defender)
    local target = self.target == "attacker" and attacker or defender
    if not target.status then
        target.status = self.status
        return { type = "status", target = self.target, status = self.status, pokemon = target }
    end
    return nil
end

-- ============================================================
-- MOVE CLASS
-- ============================================================

Class("Move")
function Move:init(name, moveType, power, accuracy, pp, effects)
    self.name = name
    self.type = moveType
    self.power = power
    self.accuracy = accuracy
    self.pp = pp
    self.maxPP = pp
    self.category = power > 0 and getMoveCategory(moveType) or "status"
    self.effects = effects
end

-- ============================================================
-- MOVE DATA
-- ============================================================

moveData = {
    pound = Move("POUND", "normal", 40, 100, 35, nil),
    karateChop = Move("KARATE CHOP", "fighting", 50, 100, 25, nil),
    doubleSlap = Move("DOUBLE SLAP", "normal", 15, 85, 10, nil),
    cometPunch = Move("COMET PUNCH", "normal", 18, 85, 15, nil),
    megaPunch = Move("MEGA PUNCH", "normal", 80, 85, 20, nil),
    payDay = Move("PAY DAY", "normal", 40, 100, 20, nil),
    firePunch = Move("FIRE PUNCH", "fire", 75, 100, 15, nil),
    icePunch = Move("ICE PUNCH", "ice", 75, 100, 15, nil),
    thunderPunch = Move("THUNDER PUNCH", "electric", 75, 100, 15, nil),
    scratch = Move("SCRATCH", "normal", 40, 100, 35, nil),
    viceGrip = Move("VICE GRIP", "normal", 55, 100, 30, nil),
    guillotine = Move("GUILLOTINE", "normal", 0, 30, 5, nil),
    razorWind = Move("RAZOR WIND", "normal", 80, 100, 10, nil),
    swordsDance = Move("SWORDS DANCE", "normal", 0, 0, 20, { StatChange("attacker", "atk", 2) }),
    gust = Move("GUST", "flying", 40, 100, 35, nil),
    wingAttack = Move("WING ATTACK", "flying", 60, 100, 35, nil),
    whirlwind = Move("WHIRLWIND", "normal", 0, 0, 20, nil),
    bind = Move("BIND", "normal", 15, 85, 20, nil),
    slam = Move("SLAM", "normal", 80, 75, 20, nil),
    vineWhip = Move("VINE WHIP", "grass", 45, 100, 25, nil),
    stomp = Move("STOMP", "normal", 65, 100, 20, nil),
    doubleKick = Move("DOUBLE KICK", "fighting", 30, 100, 30, nil),
    megaKick = Move("MEGA KICK", "normal", 120, 75, 5, nil),
    jumpKick = Move("JUMP KICK", "fighting", 100, 95, 10, nil),
    rollingKick = Move("ROLLING KICK", "fighting", 60, 85, 15, nil),
    sandAttack = Move("SAND ATTACK", "ground", 0, 100, 15, nil),
    headbutt = Move("HEADBUTT", "normal", 70, 100, 15, { ConditionalEffect(30, StatusEffect("defender", "flinch")) }),
    hornAttack = Move("HORN ATTACK", "normal", 65, 100, 25, nil),
    furyAttack = Move("FURY ATTACK", "normal", 15, 85, 20, nil),
    hornDrill = Move("HORN DRILL", "normal", 0, 30, 5, nil),
    tackle = Move("TACKLE", "normal", 40, 100, 35, nil),
    bodySlam = Move("BODY SLAM", "normal", 85, 100, 15, nil),
    wrap = Move("WRAP", "normal", 15, 90, 20, nil),
    takeDown = Move("TAKE DOWN", "normal", 90, 85, 20, nil),
    thrash = Move("THRASH", "normal", 120, 100, 10, nil),
    doubleEdge = Move("DOUBLE EDGE", "normal", 120, 100, 15, nil),
    tailWhip = Move("TAIL WHIP", "normal", 0, 100, 30, { StatChange("defender", "def", -1) }),
    poisonSting = Move("POISON STING", "poison", 15, 100, 35, { ConditionalEffect(30, StatusEffect("defender", "poison")) }),
    twineedle = Move("TWINEEDLE", "bug", 25, 100, 20, nil),
    pinMissile = Move("PIN MISSILE", "bug", 25, 95, 20, nil),
    leer = Move("LEER", "normal", 0, 100, 30, { StatChange("defender", "def", -1) }),
    bite = Move("BITE", "dark", 60, 100, 25, { ConditionalEffect(30, StatusEffect("defender", "flinch")) }),
    growl = Move("GROWL", "normal", 0, 100, 40, { StatChange("defender", "atk", -1) }),
    roar = Move("ROAR", "normal", 0, 0, 20, nil),
    sing = Move("SING", "normal", 0, 55, 15, { StatusEffect("defender", "sleep") }),
    supersonic = Move("SUPERSONIC", "normal", 0, 55, 20, nil),
    sonicBoom = Move("SONIC BOOM", "normal", 0, 90, 20, nil),
    disable = Move("DISABLE", "normal", 0, 100, 20, nil),
    acid = Move("ACID", "poison", 40, 100, 30, nil),
    ember = Move("EMBER", "fire", 40, 100, 25, { ConditionalEffect(10, StatusEffect("defender", "burn")) }),
    flamethrower = Move("FLAMETHROWER", "fire", 90, 100, 15, { ConditionalEffect(10, StatusEffect("defender", "burn")) }),
    mist = Move("MIST", "ice", 0, 0, 30, nil),
    waterGun = Move("WATER GUN", "water", 40, 100, 25, nil),
    hydroPump = Move("HYDRO PUMP", "water", 110, 80, 5, nil),
    iceBeam = Move("ICE BEAM", "ice", 90, 100, 10, { ConditionalEffect(10, StatusEffect("defender", "freeze")) }),
    blizzard = Move("BLIZZARD", "ice", 110, 70, 5, { ConditionalEffect(10, StatusEffect("defender", "freeze")) }),
    psybeam = Move("PSYBEAM", "psychic", 65, 100, 20, nil),
    bubbleBeam = Move("BUBBLE BEAM", "water", 65, 100, 20, nil),
    auroraBeam = Move("AURORA BEAM", "ice", 65, 100, 20, nil),
    hyperBeam = Move("HYPER BEAM", "normal", 150, 90, 5, nil),
    peck = Move("PECK", "flying", 35, 100, 35, nil),
    drillPeck = Move("DRILL PECK", "flying", 80, 100, 20, nil),
    submission = Move("SUBMISSION", "fighting", 80, 80, 20, nil),
    lowKick = Move("LOW KICK", "fighting", 0, 100, 20, nil),
    counter = Move("COUNTER", "fighting", 0, 100, 20, nil),
    seismicToss = Move("SEISMIC TOSS", "fighting", 0, 100, 20, nil),
    absorb = Move("ABSORB", "grass", 20, 100, 25, nil),
    megaDrain = Move("MEGA DRAIN", "grass", 40, 100, 15, nil),
    leechSeed = Move("LEECH SEED", "grass", 0, 90, 10, nil),
    growth = Move("GROWTH", "normal", 0, 0, 20, { StatChange("attacker", "atk", 1), StatChange("attacker", "spc", 1) }),
    razorLeaf = Move("RAZOR LEAF", "grass", 55, 95, 25, nil),
    solarBeam = Move("SOLAR BEAM", "grass", 120, 100, 10, nil),
    poisonPowder = Move("POISON POWDER", "poison", 0, 75, 35, { StatusEffect("defender", "poison") }),
    stunSpore = Move("STUN SPORE", "grass", 0, 75, 30, { StatusEffect("defender", "paralyze") }),
    sleepPowder = Move("SLEEP POWDER", "grass", 0, 75, 15, { StatusEffect("defender", "sleep") }),
    petalDance = Move("PETAL DANCE", "grass", 120, 100, 10, nil),
    stringShot = Move("STRING SHOT", "bug", 0, 95, 40, nil),
    dragonRage = Move("DRAGON RAGE", "dragon", 0, 100, 10, nil),
    fireSpin = Move("FIRE SPIN", "fire", 35, 85, 15, nil),
    thunderShock = Move("THUNDER SHOCK", "electric", 40, 100, 30, { ConditionalEffect(10, StatusEffect("defender", "paralyze")) }),
    thunderbolt = Move("THUNDERBOLT", "electric", 90, 100, 15, { ConditionalEffect(10, StatusEffect("defender", "paralyze")) }),
    thunderWave = Move("THUNDER WAVE", "electric", 0, 90, 20, { StatusEffect("defender", "paralyze") }),
    thunder = Move("THUNDER", "electric", 110, 70, 10, { ConditionalEffect(30, StatusEffect("defender", "paralyze")) }),
    rockThrow = Move("ROCK THROW", "rock", 50, 90, 15, nil),
    earthquake = Move("EARTHQUAKE", "ground", 100, 100, 10, nil),
    fissure = Move("FISSURE", "ground", 0, 30, 5, nil),
    dig = Move("DIG", "ground", 80, 100, 10, nil),
    confusion = Move("CONFUSION", "psychic", 50, 100, 25, nil),
    psychic = Move("PSYCHIC", "psychic", 90, 100, 10, nil),
    hypnosis = Move("HYPNOSIS", "psychic", 0, 60, 20, { StatusEffect("defender", "sleep") }),
    meditate = Move("MEDITATE", "psychic", 0, 0, 40, nil),
    agility = Move("AGILITY", "psychic", 0, 0, 30, { StatChange("attacker", "spd", 2) }),
    quickAttack = Move("QUICK ATTACK", "normal", 40, 100, 30, nil),
    rage = Move("RAGE", "normal", 20, 100, 20, nil),
    teleport = Move("TELEPORT", "psychic", 0, 0, 20, nil),
    nightShade = Move("NIGHT SHADE", "ghost", 0, 100, 15, nil),
    mimic = Move("MIMIC", "normal", 0, 0, 10, nil),
    screech = Move("SCREECH", "normal", 0, 85, 40, { StatChange("defender", "def", -2) }),
    doubleTeam = Move("DOUBLE TEAM", "normal", 0, 0, 15, nil),
    recover = Move("RECOVER", "normal", 0, 0, 10, nil),
    harden = Move("HARDEN", "normal", 0, 0, 30, nil),
    minimize = Move("MINIMIZE", "normal", 0, 0, 10, nil),
    smokescreen = Move("SMOKESCREEN", "normal", 0, 100, 20, nil),
    confuseRay = Move("CONFUSE RAY", "ghost", 0, 100, 10, nil),
    withdraw = Move("WITHDRAW", "water", 0, 0, 40, nil),
    defenseCurl = Move("DEFENSE CURL", "normal", 0, 0, 40, nil),
    barrier = Move("BARRIER", "psychic", 0, 0, 20, nil),
    lightScreen = Move("LIGHT SCREEN", "psychic", 0, 0, 30, nil),
    haze = Move("HAZE", "ice", 0, 0, 30, nil),
    reflect = Move("REFLECT", "psychic", 0, 0, 20, nil),
    focusEnergy = Move("FOCUS ENERGY", "normal", 0, 0, 30, nil),
    metronome = Move("METRONOME", "normal", 0, 0, 10, nil),
    mirrorMove = Move("MIRROR MOVE", "flying", 0, 0, 20, nil),
    selfDestruct = Move("SELF DESTRUCT", "normal", 200, 100, 5, nil),
    eggBomb = Move("EGG BOMB", "normal", 100, 75, 10, nil),
    lick = Move("LICK", "ghost", 30, 100, 30, nil),
    smog = Move("SMOG", "poison", 30, 70, 20, nil),
    sludge = Move("SLUDGE", "poison", 65, 100, 20, nil),
    boneClub = Move("BONE CLUB", "ground", 65, 85, 20, nil),
    fireBlast = Move("FIRE BLAST", "fire", 110, 85, 5, { ConditionalEffect(10, StatusEffect("defender", "burn")) }),
    waterfall = Move("WATERFALL", "water", 80, 100, 15, nil),
    clamp = Move("CLAMP", "water", 35, 85, 15, nil),
    swift = Move("SWIFT", "normal", 60, 0, 20, nil),
    skullBash = Move("SKULL BASH", "normal", 130, 100, 10, nil),
    spikeCannon = Move("SPIKE CANNON", "normal", 20, 100, 15, nil),
    constrict = Move("CONSTRICT", "normal", 10, 100, 35, nil),
    amnesia = Move("AMNESIA", "psychic", 0, 0, 20, { StatChange("attacker", "spc", 2) }),
    kinesis = Move("KINESIS", "psychic", 0, 80, 15, nil),
    softBoiled = Move("SOFT BOILED", "normal", 0, 0, 10, nil),
    highJumpKick = Move("HIGH JUMP KICK", "fighting", 130, 90, 10, nil),
    glare = Move("GLARE", "normal", 0, 100, 30, nil),
    dreamEater = Move("DREAM EATER", "psychic", 100, 100, 15, nil),
    poisonGas = Move("POISON GAS", "poison", 0, 90, 40, nil),
    barrage = Move("BARRAGE", "normal", 15, 85, 20, nil),
    leechLife = Move("LEECH LIFE", "bug", 80, 100, 10, nil),
    lovelyKiss = Move("LOVELY KISS", "normal", 0, 75, 10, nil),
    skyAttack = Move("SKY ATTACK", "flying", 140, 90, 5, nil),
    transform = Move("TRANSFORM", "normal", 0, 0, 10, nil),
    bubble = Move("BUBBLE", "water", 40, 100, 30, nil),
    dizzyPunch = Move("DIZZY PUNCH", "normal", 70, 100, 10, nil),
    spore = Move("SPORE", "grass", 0, 100, 15, nil),
    splash = Move("SPLASH", "normal", 0, 0, 40, nil),
    acidArmor = Move("ACID ARMOR", "poison", 0, 0, 20, nil),
    crabhammer = Move("CRABHAMMER", "water", 100, 90, 10, nil),
    explosion = Move("EXPLOSION", "normal", 250, 100, 5, nil),
    furySwipes = Move("FURY SWIPES", "normal", 18, 80, 15, nil),
    bonemerang = Move("BONEMERANG", "ground", 50, 90, 10, nil),
    rest = Move("REST", "psychic", 0, 0, 10, nil),
    rockSlide = Move("ROCK SLIDE", "rock", 75, 90, 10, nil),
    hyperFang = Move("HYPER FANG", "normal", 80, 90, 15, nil),
    sharpen = Move("SHARPEN", "normal", 0, 0, 30, nil),
    conversion = Move("CONVERSION", "normal", 0, 0, 30, nil),
    triAttack = Move("TRI ATTACK", "normal", 80, 100, 10, nil),
    superFang = Move("SUPER FANG", "normal", 0, 90, 10, nil),
    slash = Move("SLASH", "normal", 70, 100, 20, nil),
    substitute = Move("SUBSTITUTE", "normal", 0, 0, 10, nil),
    mindReader = Move("MIND READER", "normal", 0, 0, 5, nil),
    nightmare = Move("NIGHTMARE", "ghost", 0, 100, 15, nil),
    flameWheel = Move("FLAME WHEEL", "fire", 60, 100, 25, nil),
    snore = Move("SNORE", "normal", 50, 100, 15, nil),
    curse = Move("CURSE", "ghost", 0, 0, 10, nil),
    flail = Move("FLAIL", "normal", 0, 100, 15, nil),
    conversion2 = Move("CONVERSION 2", "normal", 0, 0, 30, nil),
    reversal = Move("REVERSAL", "fighting", 0, 100, 15, nil),
    spite = Move("SPITE", "ghost", 0, 100, 10, nil),
    powderSnow = Move("POWDER SNOW", "ice", 40, 100, 25, nil),
    protect = Move("PROTECT", "normal", 0, 0, 10, nil),
    machPunch = Move("MACH PUNCH", "fighting", 40, 100, 30, nil),
    scaryFace = Move("SCARY FACE", "normal", 0, 100, 10, { StatChange("defender", "spd", -2) }),
    feintAttack = Move("FEINT ATTACK", "dark", 60, 0, 20, nil),
    bellyDrum = Move("BELLY DRUM", "normal", 0, 0, 10, nil),
    sludgeBomb = Move("SLUDGE BOMB", "poison", 90, 100, 10, { ConditionalEffect(30, StatusEffect("defender", "poison")) }),
    mudSlap = Move("MUD SLAP", "ground", 20, 100, 10, nil),
    spikes = Move("SPIKES", "ground", 0, 0, 20, nil),
    zapCannon = Move("ZAP CANNON", "electric", 120, 50, 5, nil),
    foresight = Move("FORESIGHT", "normal", 0, 0, 40, nil),
    destinyBond = Move("DESTINY BOND", "ghost", 0, 0, 5, nil),
    perishSong = Move("PERISH SONG", "normal", 0, 0, 5, nil),
    icyWind = Move("ICY WIND", "ice", 55, 95, 15, nil),
    detect = Move("DETECT", "fighting", 0, 0, 5, nil),
    boneRush = Move("BONE RUSH", "ground", 25, 90, 10, nil),
    lockOn = Move("LOCK ON", "normal", 0, 0, 5, nil),
    outrage = Move("OUTRAGE", "dragon", 120, 100, 10, nil),
    sandstorm = Move("SANDSTORM", "rock", 0, 0, 10, nil),
    gigaDrain = Move("GIGA DRAIN", "grass", 75, 100, 10, nil),
    endure = Move("ENDURE", "normal", 0, 0, 10, nil),
    rollout = Move("ROLLOUT", "rock", 30, 90, 20, nil),
    falseSwipe = Move("FALSE SWIPE", "normal", 40, 100, 40, nil),
    swagger = Move("SWAGGER", "normal", 0, 85, 15, nil),
    spark = Move("SPARK", "electric", 65, 100, 20, nil),
    furyCutter = Move("FURY CUTTER", "bug", 40, 95, 20, nil),
    meanLook = Move("MEAN LOOK", "normal", 0, 0, 5, nil),
    sleepTalk = Move("SLEEP TALK", "normal", 0, 0, 10, nil),
    safeguard = Move("SAFEGUARD", "normal", 0, 0, 25, nil),
    magnitude = Move("MAGNITUDE", "ground", 0, 100, 30, nil),
    dynamicPunch = Move("DYNAMIC PUNCH", "fighting", 100, 50, 5, nil),
    megahorn = Move("MEGAHORN", "bug", 120, 85, 10, nil),
    dragonBreath = Move("DRAGON BREATH", "dragon", 60, 100, 20, nil),
    batonPass = Move("BATON PASS", "normal", 0, 0, 40, nil),
    encore = Move("ENCORE", "normal", 0, 100, 5, nil),
    pursuit = Move("PURSUIT", "dark", 40, 100, 20, nil),
    rapidSpin = Move("RAPID SPIN", "normal", 50, 100, 40, nil),
    sweetScent = Move("SWEET SCENT", "normal", 0, 100, 20, nil),
    ironTail = Move("IRON TAIL", "steel", 100, 75, 15, nil),
    metalClaw = Move("METAL CLAW", "steel", 50, 95, 35, nil),
    vitalThrow = Move("VITAL THROW", "fighting", 70, 0, 10, nil),
    synthesis = Move("SYNTHESIS", "grass", 0, 0, 5, nil),
    moonlight = Move("MOONLIGHT", "fairy", 0, 0, 5, nil),
    crossChop = Move("CROSS CHOP", "fighting", 100, 80, 5, nil),
    twister = Move("TWISTER", "dragon", 40, 100, 20, nil),
    rainDance = Move("RAIN DANCE", "water", 0, 0, 5, nil),
    sunnyDay = Move("SUNNY DAY", "fire", 0, 0, 5, nil),
    crunch = Move("CRUNCH", "dark", 80, 100, 15, { ConditionalEffect(20, StatChange("defender", "def", -1)) }),
    mirrorCoat = Move("MIRROR COAT", "psychic", 0, 100, 20, nil),
    psychUp = Move("PSYCH UP", "normal", 0, 0, 10, nil),
    extremeSpeed = Move("EXTREME SPEED", "normal", 80, 100, 5, nil),
    ancientPower = Move("ANCIENT POWER", "rock", 60, 100, 5, nil),
    shadowBall = Move("SHADOW BALL", "ghost", 80, 100, 15, nil),
    futureSight = Move("FUTURE SIGHT", "psychic", 120, 100, 10, nil),
    whirlpool = Move("WHIRLPOOL", "water", 35, 85, 15, nil),
    fakeOut = Move("FAKE OUT", "normal", 40, 100, 10, nil),
    uproar = Move("UPROAR", "normal", 90, 100, 10, nil),
    stockpile = Move("STOCKPILE", "normal", 0, 0, 20, nil),
    spitUp = Move("SPIT UP", "normal", 0, 100, 10, nil),
    swallow = Move("SWALLOW", "normal", 0, 0, 10, nil),
    heatWave = Move("HEAT WAVE", "fire", 95, 90, 10, nil),
    hail = Move("HAIL", "ice", 0, 0, 10, nil),
    flatter = Move("FLATTER", "dark", 0, 100, 15, nil),
    willOWisp = Move("WILL O WISP", "fire", 0, 85, 15, { StatusEffect("defender", "burn") }),
    memento = Move("MEMENTO", "dark", 0, 100, 10, nil),
    focusPunch = Move("FOCUS PUNCH", "fighting", 150, 100, 20, nil),
    followMe = Move("FOLLOW ME", "normal", 0, 0, 20, nil),
    charge = Move("CHARGE", "electric", 0, 0, 20, nil),
    taunt = Move("TAUNT", "dark", 0, 100, 20, nil),
    helpingHand = Move("HELPING HAND", "normal", 0, 0, 20, nil),
    trick = Move("TRICK", "psychic", 0, 100, 10, nil),
    rolePlay = Move("ROLE PLAY", "psychic", 0, 0, 10, nil),
    ingrain = Move("INGRAIN", "grass", 0, 0, 20, nil),
    superpower = Move("SUPERPOWER", "fighting", 120, 100, 5, nil),
    magicCoat = Move("MAGIC COAT", "psychic", 0, 0, 15, nil),
    recycle = Move("RECYCLE", "normal", 0, 0, 10, nil),
    revenge = Move("REVENGE", "fighting", 60, 100, 10, nil),
    brickBreak = Move("BRICK BREAK", "fighting", 75, 100, 15, nil),
    yawn = Move("YAWN", "normal", 0, 0, 10, nil),
    knockOff = Move("KNOCK OFF", "dark", 65, 100, 20, nil),
    endeavor = Move("ENDEAVOR", "normal", 0, 100, 5, nil),
    imprison = Move("IMPRISON", "psychic", 0, 0, 10, nil),
    refresh = Move("REFRESH", "normal", 0, 0, 20, nil),
    grudge = Move("GRUDGE", "ghost", 0, 0, 5, nil),
    dive = Move("DIVE", "water", 80, 100, 10, nil),
    camouflage = Move("CAMOUFLAGE", "normal", 0, 0, 20, nil),
    featherDance = Move("FEATHER DANCE", "flying", 0, 100, 15, nil),
    blazeKick = Move("BLAZE KICK", "fire", 85, 90, 10, nil),
    mudSport = Move("MUD SPORT", "ground", 0, 0, 15, nil),
    slackOff = Move("SLACK OFF", "normal", 0, 0, 10, nil),
    hyperVoice = Move("HYPER VOICE", "normal", 90, 100, 10, nil),
    poisonFang = Move("POISON FANG", "poison", 50, 100, 15, nil),
    crushClaw = Move("CRUSH CLAW", "normal", 75, 95, 10, nil),
    meteorMash = Move("METEOR MASH", "steel", 90, 90, 10, nil),
    astonish = Move("ASTONISH", "ghost", 30, 100, 15, nil),
    aromatherapy = Move("AROMATHERAPY", "grass", 0, 0, 5, nil),
    fakeTears = Move("FAKE TEARS", "dark", 0, 100, 20, nil),
    airCutter = Move("AIR CUTTER", "flying", 60, 95, 25, nil),
    odorSleuth = Move("ODOR SLEUTH", "normal", 0, 0, 40, nil),
    rockTomb = Move("ROCK TOMB", "rock", 60, 95, 15, nil),
    silverWind = Move("SILVER WIND", "bug", 60, 100, 5, nil),
    metalSound = Move("METAL SOUND", "steel", 0, 85, 40, nil),
    tickle = Move("TICKLE", "normal", 0, 100, 20, nil),
    cosmicPower = Move("COSMIC POWER", "psychic", 0, 0, 20, nil),
    signalBeam = Move("SIGNAL BEAM", "bug", 75, 100, 15, nil),
    shadowPunch = Move("SHADOW PUNCH", "ghost", 60, 0, 20, nil),
    extrasensory = Move("EXTRASENSORY", "psychic", 80, 100, 20, nil),
    skyUppercut = Move("SKY UPPERCUT", "fighting", 85, 90, 15, nil),
    sandTomb = Move("SAND TOMB", "ground", 35, 85, 15, nil),
    sheerCold = Move("SHEER COLD", "ice", 0, 30, 5, nil),
    muddyWater = Move("MUDDY WATER", "water", 90, 85, 10, nil),
    bulletSeed = Move("BULLET SEED", "grass", 25, 100, 30, nil),
    aerialAce = Move("AERIAL ACE", "flying", 60, 0, 20, nil),
    icicleSpear = Move("ICICLE SPEAR", "ice", 25, 100, 30, nil),
    ironDefense = Move("IRON DEFENSE", "steel", 0, 0, 15, nil),
    block = Move("BLOCK", "normal", 0, 0, 5, nil),
    dragonClaw = Move("DRAGON CLAW", "dragon", 80, 100, 15, nil),
    bounce = Move("BOUNCE", "flying", 85, 85, 5, nil),
    mudShot = Move("MUD SHOT", "ground", 55, 95, 15, nil),
    covet = Move("COVET", "normal", 60, 100, 25, nil),
    magicalLeaf = Move("MAGICAL LEAF", "grass", 60, 0, 20, nil),
    waterSport = Move("WATER SPORT", "water", 0, 0, 15, nil),
    calmMind = Move("CALM MIND", "psychic", 0, 0, 20, { StatChange("attacker", "spc", 1), StatChange("attacker", "def", 1) }),
    leafBlade = Move("LEAF BLADE", "grass", 90, 100, 15, nil),
    dragonDance = Move("DRAGON DANCE", "dragon", 0, 0, 20, { StatChange("attacker", "atk", 1), StatChange("attacker", "spd", 1) }),
    rockBlast = Move("ROCK BLAST", "rock", 25, 90, 10, nil),
    shockWave = Move("SHOCK WAVE", "electric", 60, 0, 20, nil),
    waterPulse = Move("WATER PULSE", "water", 60, 100, 20, nil),
    roost = Move("ROOST", "flying", 0, 0, 10, nil),
    gravity = Move("GRAVITY", "psychic", 0, 0, 5, nil),
    miracleEye = Move("MIRACLE EYE", "psychic", 0, 0, 40, nil),
    wakeUpSlap = Move("WAKE UP SLAP", "fighting", 70, 100, 10, nil),
    hammerArm = Move("HAMMER ARM", "fighting", 100, 90, 10, nil),
    gyroBall = Move("GYRO BALL", "steel", 0, 100, 5, nil),
    healingWish = Move("HEALING WISH", "psychic", 0, 0, 10, nil),
    brine = Move("BRINE", "water", 65, 100, 10, nil),
    naturalGift = Move("NATURAL GIFT", "normal", 0, 100, 15, nil),
    feint = Move("FEINT", "normal", 30, 100, 10, nil),
    pluck = Move("PLUCK", "flying", 60, 100, 20, nil),
    tailwind = Move("TAILWIND", "flying", 0, 0, 15, nil),
    acupressure = Move("ACUPRESSURE", "normal", 0, 0, 30, nil),
    closeCombat = Move("CLOSE COMBAT", "fighting", 120, 100, 5, nil),
    payback = Move("PAYBACK", "dark", 50, 100, 10, nil),
    assurance = Move("ASSURANCE", "dark", 60, 100, 10, nil),
    fling = Move("FLING", "dark", 0, 100, 10, nil),
    trumpCard = Move("TRUMP CARD", "normal", 0, 0, 5, nil),
    wringOut = Move("WRING OUT", "normal", 0, 100, 5, nil),
    gastroAcid = Move("GASTRO ACID", "poison", 0, 100, 10, nil),
    luckyChant = Move("LUCKY CHANT", "normal", 0, 0, 30, nil),
    meFirst = Move("ME FIRST", "normal", 0, 0, 20, nil),
    copycat = Move("COPYCAT", "normal", 0, 0, 20, nil),
    powerSwap = Move("POWER SWAP", "psychic", 0, 0, 10, nil),
    guardSwap = Move("GUARD SWAP", "psychic", 0, 0, 10, nil),
    punishment = Move("PUNISHMENT", "dark", 0, 100, 5, nil),
    lastResort = Move("LAST RESORT", "normal", 140, 100, 5, nil),
    worrySeed = Move("WORRY SEED", "grass", 0, 100, 10, nil),
    suckerPunch = Move("SUCKER PUNCH", "dark", 70, 100, 5, nil),
    toxicSpikes = Move("TOXIC SPIKES", "poison", 0, 0, 20, nil),
    aquaRing = Move("AQUA RING", "water", 0, 0, 20, nil),
    magnetRise = Move("MAGNET RISE", "electric", 0, 0, 10, nil),
    flareBlitz = Move("FLARE BLITZ", "fire", 120, 100, 15, nil),
    auraSphere = Move("AURA SPHERE", "fighting", 80, 0, 20, nil),
    rockPolish = Move("ROCK POLISH", "rock", 0, 0, 20, nil),
    poisonJab = Move("POISON JAB", "poison", 80, 100, 20, { ConditionalEffect(30, StatusEffect("defender", "poison")) }),
    darkPulse = Move("DARK PULSE", "dark", 80, 100, 15, nil),
    nightSlash = Move("NIGHT SLASH", "dark", 70, 100, 15, nil),
    aquaTail = Move("AQUA TAIL", "water", 90, 90, 10, nil),
    seedBomb = Move("SEED BOMB", "grass", 80, 100, 15, nil),
    airSlash = Move("AIR SLASH", "flying", 75, 95, 15, nil),
    xScissor = Move("X SCISSOR", "bug", 80, 100, 15, nil),
    bugBuzz = Move("BUG BUZZ", "bug", 90, 100, 10, nil),
    dragonPulse = Move("DRAGON PULSE", "dragon", 85, 100, 10, nil),
    dragonRush = Move("DRAGON RUSH", "dragon", 100, 75, 10, nil),
    powerGem = Move("POWER GEM", "rock", 80, 100, 20, nil),
    vacuumWave = Move("VACUUM WAVE", "fighting", 40, 100, 30, nil),
    braveBird = Move("BRAVE BIRD", "flying", 120, 100, 15, nil),
    earthPower = Move("EARTH POWER", "ground", 90, 100, 10, nil),
    switcheroo = Move("SWITCHEROO", "dark", 0, 100, 10, nil),
    gigaImpact = Move("GIGA IMPACT", "normal", 150, 90, 5, nil),
    nastyPlot = Move("NASTY PLOT", "dark", 0, 0, 20, { StatChange("attacker", "spc", 2) }),
    bulletPunch = Move("BULLET PUNCH", "steel", 40, 100, 30, nil),
    avalanche = Move("AVALANCHE", "ice", 60, 100, 10, nil),
    iceShard = Move("ICE SHARD", "ice", 40, 100, 30, nil),
    shadowClaw = Move("SHADOW CLAW", "ghost", 70, 100, 15, nil),
    thunderFang = Move("THUNDER FANG", "electric", 65, 95, 15, nil),
    iceFang = Move("ICE FANG", "ice", 65, 95, 15, nil),
    fireFang = Move("FIRE FANG", "fire", 65, 95, 15, nil),
    mudBomb = Move("MUD BOMB", "ground", 65, 85, 10, nil),
    psychoCut = Move("PSYCHO CUT", "psychic", 70, 100, 20, nil),
    zenHeadbutt = Move("ZEN HEADBUTT", "psychic", 80, 90, 15, nil),
    mirrorShot = Move("MIRROR SHOT", "steel", 65, 85, 10, nil),
    flashCannon = Move("FLASH CANNON", "steel", 80, 100, 10, nil),
    discharge = Move("DISCHARGE", "electric", 80, 100, 15, nil),
    lavaPlume = Move("LAVA PLUME", "fire", 80, 100, 15, nil),
    leafStorm = Move("LEAF STORM", "grass", 130, 90, 5, nil),
    powerWhip = Move("POWER WHIP", "grass", 120, 85, 10, nil),
    crossPoison = Move("CROSS POISON", "poison", 70, 100, 20, nil),
    gunkShot = Move("GUNK SHOT", "poison", 120, 80, 5, nil),
    ironHead = Move("IRON HEAD", "steel", 80, 100, 15, nil),
    magnetBomb = Move("MAGNET BOMB", "steel", 60, 0, 20, nil),
    stoneEdge = Move("STONE EDGE", "rock", 100, 80, 5, nil),
    captivate = Move("CAPTIVATE", "normal", 0, 100, 20, nil),
    stealthRock = Move("STEALTH ROCK", "rock", 0, 0, 20, nil),
    bugBite = Move("BUG BITE", "bug", 60, 100, 20, nil),
    chargeBeam = Move("CHARGE BEAM", "electric", 50, 90, 10, nil),
    woodHammer = Move("WOOD HAMMER", "grass", 120, 100, 15, nil),
    aquaJet = Move("AQUA JET", "water", 40, 100, 20, nil),
    doubleHit = Move("DOUBLE HIT", "normal", 35, 90, 10, nil),
    wideGuard = Move("WIDE GUARD", "rock", 0, 0, 10, nil),
    wonderRoom = Move("WONDER ROOM", "psychic", 0, 0, 10, nil),
    psyshock = Move("PSYSHOCK", "psychic", 80, 100, 10, nil),
    ragePowder = Move("RAGE POWDER", "bug", 0, 0, 20, nil),
    telekinesis = Move("TELEKINESIS", "psychic", 0, 0, 15, nil),
    smackDown = Move("SMACK DOWN", "rock", 50, 100, 15, nil),
    flameBurst = Move("FLAME BURST", "fire", 70, 100, 15, nil),
    sludgeWave = Move("SLUDGE WAVE", "poison", 95, 100, 10, { ConditionalEffect(10, StatusEffect("defender", "poison")) }),
    quiverDance = Move("QUIVER DANCE", "bug", 0, 0, 20, { StatChange("attacker", "spc", 1), StatChange("attacker", "spd", 1), StatChange("attacker", "def", 1) }),
    heavySlam = Move("HEAVY SLAM", "steel", 0, 100, 10, nil),
    synchronoise = Move("SYNCHRONOISE", "psychic", 120, 100, 10, nil),
    electroBall = Move("ELECTRO BALL", "electric", 0, 100, 10, nil),
    soak = Move("SOAK", "water", 0, 100, 20, nil),
    flameCharge = Move("FLAME CHARGE", "fire", 50, 100, 20, { StatChange("attacker", "atk", 1), StatChange("attacker", "spd", 2) }),
    coil = Move("COIL", "poison", 0, 0, 20, { StatChange("attacker", "atk", 1), StatChange("attacker", "def", 1), StatChange("attacker", "spc", 1), StatChange("attacker", "spd", 1) }),
    lowSweep = Move("LOW SWEEP", "fighting", 65, 100, 20, nil),
    acidSpray = Move("ACID SPRAY", "poison", 40, 100, 20, { StatChange("defender", "spc", -2) }),
    afterYou = Move("AFTER YOU", "normal", 0, 0, 15, nil),
    round = Move("ROUND", "normal", 60, 100, 15, nil),
    chipAway = Move("CHIP AWAY", "normal", 70, 100, 20, nil),
    clearSmog = Move("CLEAR SMOG", "poison", 50, 0, 15, nil),
    storedPower = Move("STORED POWER", "psychic", 20, 100, 10, nil),
    quickGuard = Move("QUICK GUARD", "fighting", 0, 0, 15, nil),
    allySwitch = Move("ALLY SWITCH", "psychic", 0, 0, 15, nil),
    shellSmash = Move("SHELL SMASH", "normal", 0, 0, 15, { StatChange("attacker", "atk", 2), StatChange("attacker", "spc", 2), StatChange("attacker", "spd", 2) }),
    healPulse = Move("HEAL PULSE", "psychic", 0, 0, 10, nil),
    hex = Move("HEX", "ghost", 65, 100, 10, nil),
    skyDrop = Move("SKY DROP", "flying", 60, 100, 10, nil),
    circleThrow = Move("CIRCLE THROW", "fighting", 60, 90, 10, nil),
    acrobatics = Move("ACROBATICS", "flying", 55, 100, 15, nil),
    reflectType = Move("REFLECT TYPE", "normal", 0, 0, 15, nil),
    retaliate = Move("RETALIATE", "normal", 70, 100, 5, nil),
    finalGambit = Move("FINAL GAMBIT", "fighting", 0, 100, 5, nil),
    bestow = Move("BESTOW", "normal", 0, 0, 15, nil),
    inferno = Move("INFERNO", "fire", 100, 50, 5, nil),
    bulldoze = Move("BULLDOZE", "ground", 60, 100, 20, nil),
    dragonTail = Move("DRAGON TAIL", "dragon", 60, 90, 10, { StatChange("defender", "spd", -1) }),
    workUp = Move("WORK UP", "normal", 0, 0, 30, { StatChange("attacker", "atk", 1), StatChange("attacker", "spc", 1) }),
    drillRun = Move("DRILL RUN", "ground", 80, 95, 10, nil),
    heartStamp = Move("HEART STAMP", "psychic", 60, 100, 25, nil),
    razorShell = Move("RAZOR SHELL", "water", 75, 95, 10, nil),
    leafTornado = Move("LEAF TORNADO", "grass", 65, 90, 10, nil),
    steamroller = Move("STEAMROLLER", "bug", 65, 100, 20, nil),
    psystrike = Move("PSYSTRIKE", "psychic", 100, 100, 10, nil),
    hurricane = Move("HURRICANE", "flying", 110, 70, 10, { ConditionalEffect(30, StatusEffect("defender", "confuse")) }),
    icicleCrash = Move("ICICLE CRASH", "ice", 85, 90, 10, { ConditionalEffect(30, StatusEffect("defender", "flinch")) }),
}
